from app.extensions import db
from app.models.food import Food

FOODS = [
    # ===== CARNES / MEATS =====
    {
        "name": "Pechuga de pollo",
        "name_en": "Chicken breast",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 165,
        "protein": 31,
        "carbs": 0,
        "fat": 3.6,
        "unit": "g",
    },
    {
        "name": "Muslo de pollo",
        "name_en": "Chicken thigh",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 209,
        "protein": 26,
        "carbs": 0,
        "fat": 11,
        "unit": "g",
    },
    {
        "name": "Pollo entero",
        "name_en": "Whole chicken",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 239,
        "protein": 27,
        "carbs": 0,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Filete de ternera",
        "name_en": "Beef steak",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 217,
        "protein": 26,
        "carbs": 0,
        "fat": 12,
        "unit": "g",
    },
    {
        "name": "Carne picada de ternera",
        "name_en": "Ground beef",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 254,
        "protein": 26,
        "carbs": 0,
        "fat": 17,
        "unit": "g",
    },
    {
        "name": "Carne picada de cerdo",
        "name_en": "Ground pork",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 297,
        "protein": 25,
        "carbs": 0,
        "fat": 21,
        "unit": "g",
    },
    {
        "name": "Lomo de cerdo",
        "name_en": "Pork loin",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 242,
        "protein": 27,
        "carbs": 0,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Chuleta de cerdo",
        "name_en": "Pork chop",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 231,
        "protein": 25,
        "carbs": 0,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Solomillo de cerdo",
        "name_en": "Pork tenderloin",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 143,
        "protein": 26,
        "carbs": 0,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Bacon",
        "name_en": "Bacon",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 541,
        "protein": 37,
        "carbs": 1,
        "fat": 42,
        "unit": "g",
    },
    {
        "name": "Jamón serrano",
        "name_en": "Serrano ham",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 241,
        "protein": 30,
        "carbs": 0,
        "fat": 13,
        "unit": "g",
    },
    {
        "name": "Jamón cocido",
        "name_en": "Cooked ham",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 107,
        "protein": 17,
        "carbs": 1,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Chorizo",
        "name_en": "Chorizo",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 455,
        "protein": 24,
        "carbs": 2,
        "fat": 38,
        "unit": "g",
    },
    {
        "name": "Salchichón",
        "name_en": "Salami",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 420,
        "protein": 22,
        "carbs": 1,
        "fat": 36,
        "unit": "g",
    },
    {
        "name": "Morcilla",
        "name_en": "Black pudding",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 379,
        "protein": 14,
        "carbs": 14,
        "fat": 30,
        "unit": "g",
    },
    {
        "name": "Salchicha Frankfurt",
        "name_en": "Frankfurt sausage",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 290,
        "protein": 12,
        "carbs": 3,
        "fat": 26,
        "unit": "g",
    },
    {
        "name": "Pavo pechuga",
        "name_en": "Turkey breast",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 135,
        "protein": 30,
        "carbs": 0,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Cordero pierna",
        "name_en": "Lamb leg",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 282,
        "protein": 25,
        "carbs": 0,
        "fat": 20,
        "unit": "g",
    },
    {
        "name": "Conejo",
        "name_en": "Rabbit",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 197,
        "protein": 29,
        "carbs": 0,
        "fat": 8,
        "unit": "g",
    },
    {
        "name": "Pato",
        "name_en": "Duck",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 337,
        "protein": 19,
        "carbs": 0,
        "fat": 28,
        "unit": "g",
    },
    {
        "name": "Hígado de ternera",
        "name_en": "Beef liver",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 135,
        "protein": 20,
        "carbs": 4,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Panceta",
        "name_en": "Pancetta",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 458,
        "protein": 14,
        "carbs": 0,
        "fat": 45,
        "unit": "g",
    },
    {
        "name": "Mortadela",
        "name_en": "Mortadella",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 311,
        "protein": 14,
        "carbs": 3,
        "fat": 27,
        "unit": "g",
    },
    {
        "name": "Fuet",
        "name_en": "Fuet sausage",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 440,
        "protein": 22,
        "carbs": 1,
        "fat": 38,
        "unit": "g",
    },
    {
        "name": "Lomo embuchado",
        "name_en": "Cured pork loin",
        "category": "Carnes",
        "category_en": "Meats",
        "calories": 207,
        "protein": 32,
        "carbs": 0,
        "fat": 9,
        "unit": "g",
    },
    # ===== PESCADOS / FISH =====
    {
        "name": "Salmón",
        "name_en": "Salmon",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 208,
        "protein": 20,
        "carbs": 0,
        "fat": 13,
        "unit": "g",
    },
    {
        "name": "Atún fresco",
        "name_en": "Fresh tuna",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 184,
        "protein": 30,
        "carbs": 0,
        "fat": 6,
        "unit": "g",
    },
    {
        "name": "Atún en lata",
        "name_en": "Canned tuna",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 116,
        "protein": 26,
        "carbs": 0,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Merluza",
        "name_en": "Hake",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 86,
        "protein": 18,
        "carbs": 0,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Bacalao fresco",
        "name_en": "Fresh cod",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 82,
        "protein": 18,
        "carbs": 0,
        "fat": 0.7,
        "unit": "g",
    },
    {
        "name": "Dorada",
        "name_en": "Sea bream",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 96,
        "protein": 18,
        "carbs": 0,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Lubina",
        "name_en": "Sea bass",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 97,
        "protein": 19,
        "carbs": 0,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Sardinas",
        "name_en": "Sardines",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 208,
        "protein": 25,
        "carbs": 0,
        "fat": 11,
        "unit": "g",
    },
    {
        "name": "Boquerones",
        "name_en": "Anchovies",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 131,
        "protein": 20,
        "carbs": 0,
        "fat": 5,
        "unit": "g",
    },
    {
        "name": "Trucha",
        "name_en": "Trout",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 148,
        "protein": 21,
        "carbs": 0,
        "fat": 6,
        "unit": "g",
    },
    {
        "name": "Rape",
        "name_en": "Monkfish",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 76,
        "protein": 16,
        "carbs": 0,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Lenguado",
        "name_en": "Sole",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 83,
        "protein": 17,
        "carbs": 0,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Caballa",
        "name_en": "Mackerel",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 205,
        "protein": 19,
        "carbs": 0,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Gambas",
        "name_en": "Prawns",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 85,
        "protein": 18,
        "carbs": 1,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Langostinos",
        "name_en": "King prawns",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 96,
        "protein": 20,
        "carbs": 1,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Mejillones",
        "name_en": "Mussels",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 86,
        "protein": 12,
        "carbs": 4,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Almejas",
        "name_en": "Clams",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 74,
        "protein": 13,
        "carbs": 3,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Pulpo",
        "name_en": "Octopus",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 82,
        "protein": 15,
        "carbs": 2,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Calamar",
        "name_en": "Squid",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 92,
        "protein": 16,
        "carbs": 3,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Sepia",
        "name_en": "Cuttlefish",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 79,
        "protein": 16,
        "carbs": 1,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Salmón ahumado",
        "name_en": "Smoked salmon",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 172,
        "protein": 25,
        "carbs": 0,
        "fat": 8,
        "unit": "g",
    },
    {
        "name": "Anchoas en lata",
        "name_en": "Canned anchovies",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 210,
        "protein": 29,
        "carbs": 0,
        "fat": 10,
        "unit": "g",
    },
    {
        "name": "Vieiras",
        "name_en": "Scallops",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 88,
        "protein": 17,
        "carbs": 3,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Pez espada",
        "name_en": "Swordfish",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 172,
        "protein": 25,
        "carbs": 0,
        "fat": 8,
        "unit": "g",
    },
    {
        "name": "Surimi",
        "name_en": "Surimi",
        "category": "Pescados",
        "category_en": "Fish",
        "calories": 99,
        "protein": 15,
        "carbs": 7,
        "fat": 1,
        "unit": "g",
    },
    # ===== LÁCTEOS / DAIRY =====
    {
        "name": "Huevo entero",
        "name_en": "Whole egg",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 155,
        "protein": 13,
        "carbs": 1,
        "fat": 11,
        "unit": "g",
    },
    {
        "name": "Clara de huevo",
        "name_en": "Egg white",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 52,
        "protein": 11,
        "carbs": 1,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Leche entera",
        "name_en": "Whole milk",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 61,
        "protein": 3,
        "carbs": 5,
        "fat": 3,
        "unit": "ml",
    },
    {
        "name": "Leche desnatada",
        "name_en": "Skimmed milk",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 35,
        "protein": 3,
        "carbs": 5,
        "fat": 0.1,
        "unit": "ml",
    },
    {
        "name": "Yogur natural",
        "name_en": "Natural yogurt",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 59,
        "protein": 4,
        "carbs": 4,
        "fat": 3,
        "unit": "g",
    },
    {
        "name": "Yogur griego",
        "name_en": "Greek yogurt",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 97,
        "protein": 9,
        "carbs": 4,
        "fat": 5,
        "unit": "g",
    },
    {
        "name": "Queso manchego",
        "name_en": "Manchego cheese",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 392,
        "protein": 26,
        "carbs": 0.5,
        "fat": 32,
        "unit": "g",
    },
    {
        "name": "Queso mozzarella",
        "name_en": "Mozzarella cheese",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 280,
        "protein": 22,
        "carbs": 2,
        "fat": 22,
        "unit": "g",
    },
    {
        "name": "Queso cheddar",
        "name_en": "Cheddar cheese",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 402,
        "protein": 25,
        "carbs": 1,
        "fat": 33,
        "unit": "g",
    },
    {
        "name": "Queso fresco",
        "name_en": "Fresh cheese",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 98,
        "protein": 12,
        "carbs": 2,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Queso parmesano",
        "name_en": "Parmesan cheese",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 431,
        "protein": 38,
        "carbs": 4,
        "fat": 29,
        "unit": "g",
    },
    {
        "name": "Nata para cocinar",
        "name_en": "Cooking cream",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 292,
        "protein": 2,
        "carbs": 3,
        "fat": 30,
        "unit": "ml",
    },
    {
        "name": "Mantequilla",
        "name_en": "Butter",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 717,
        "protein": 1,
        "carbs": 0.1,
        "fat": 81,
        "unit": "g",
    },
    {
        "name": "Kéfir",
        "name_en": "Kefir",
        "category": "Lácteos",
        "category_en": "Dairy",
        "calories": 52,
        "protein": 3.5,
        "carbs": 5,
        "fat": 2,
        "unit": "ml",
    },
    # ===== CEREALES / GRAINS =====
    {
        "name": "Arroz blanco",
        "name_en": "White rice",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 365,
        "protein": 7,
        "carbs": 80,
        "fat": 0.7,
        "unit": "g",
    },
    {
        "name": "Arroz integral",
        "name_en": "Brown rice",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 362,
        "protein": 8,
        "carbs": 76,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Pasta seca",
        "name_en": "Dry pasta",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 371,
        "protein": 13,
        "carbs": 75,
        "fat": 1.5,
        "unit": "g",
    },
    {
        "name": "Pan blanco",
        "name_en": "White bread",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 265,
        "protein": 9,
        "carbs": 51,
        "fat": 3,
        "unit": "g",
    },
    {
        "name": "Pan integral",
        "name_en": "Whole grain bread",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 247,
        "protein": 13,
        "carbs": 41,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Avena",
        "name_en": "Oats",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 389,
        "protein": 17,
        "carbs": 66,
        "fat": 7,
        "unit": "g",
    },
    {
        "name": "Harina de trigo",
        "name_en": "Wheat flour",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 364,
        "protein": 10,
        "carbs": 76,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Quinoa",
        "name_en": "Quinoa",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 368,
        "protein": 14,
        "carbs": 64,
        "fat": 6,
        "unit": "g",
    },
    {
        "name": "Cuscús",
        "name_en": "Couscous",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 376,
        "protein": 13,
        "carbs": 77,
        "fat": 0.6,
        "unit": "g",
    },
    {
        "name": "Maíz",
        "name_en": "Corn",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 365,
        "protein": 9,
        "carbs": 74,
        "fat": 5,
        "unit": "g",
    },
    {
        "name": "Mijo",
        "name_en": "Millet",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 378,
        "protein": 11,
        "carbs": 73,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Espelta",
        "name_en": "Spelt",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 338,
        "protein": 15,
        "carbs": 70,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Pan rallado",
        "name_en": "Breadcrumbs",
        "category": "Cereales",
        "category_en": "Grains",
        "calories": 395,
        "protein": 11,
        "carbs": 73,
        "fat": 5,
        "unit": "g",
    },
    # ===== LEGUMBRES / LEGUMES =====
    {
        "name": "Lentejas",
        "name_en": "Lentils",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 353,
        "protein": 25,
        "carbs": 60,
        "fat": 2,
        "unit": "g",
    },
    {
        "name": "Garbanzos",
        "name_en": "Chickpeas",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 364,
        "protein": 19,
        "carbs": 61,
        "fat": 6,
        "unit": "g",
    },
    {
        "name": "Alubias blancas",
        "name_en": "White beans",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 333,
        "protein": 23,
        "carbs": 60,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Alubias negras",
        "name_en": "Black beans",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 341,
        "protein": 22,
        "carbs": 63,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Judías verdes",
        "name_en": "Green beans",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 31,
        "protein": 2,
        "carbs": 7,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Guisantes",
        "name_en": "Peas",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 81,
        "protein": 5,
        "carbs": 14,
        "fat": 0.4,
        "unit": "g",
    },
    {
        "name": "Soja",
        "name_en": "Soybeans",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 446,
        "protein": 36,
        "carbs": 30,
        "fat": 20,
        "unit": "g",
    },
    {
        "name": "Tofu",
        "name_en": "Tofu",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 76,
        "protein": 8,
        "carbs": 2,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Edamame",
        "name_en": "Edamame",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 121,
        "protein": 11,
        "carbs": 9,
        "fat": 5,
        "unit": "g",
    },
    {
        "name": "Hummus",
        "name_en": "Hummus",
        "category": "Legumbres",
        "category_en": "Legumes",
        "calories": 177,
        "protein": 8,
        "carbs": 20,
        "fat": 8,
        "unit": "g",
    },
    # ===== VERDURAS / VEGETABLES =====
    {
        "name": "Tomate",
        "name_en": "Tomato",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 18,
        "protein": 0.9,
        "carbs": 3.9,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Cebolla",
        "name_en": "Onion",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 40,
        "protein": 1.1,
        "carbs": 9,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Ajo",
        "name_en": "Garlic",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 149,
        "protein": 6,
        "carbs": 33,
        "fat": 0.5,
        "unit": "g",
    },
    {
        "name": "Pimiento rojo",
        "name_en": "Red pepper",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 31,
        "protein": 1,
        "carbs": 6,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Pimiento verde",
        "name_en": "Green pepper",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 20,
        "protein": 0.9,
        "carbs": 4,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Zanahoria",
        "name_en": "Carrot",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 41,
        "protein": 0.9,
        "carbs": 10,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Patata",
        "name_en": "Potato",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 77,
        "protein": 2,
        "carbs": 17,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Boniato",
        "name_en": "Sweet potato",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 86,
        "protein": 1.6,
        "carbs": 20,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Calabacín",
        "name_en": "Zucchini",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 17,
        "protein": 1.2,
        "carbs": 3.1,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Berenjena",
        "name_en": "Eggplant",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 25,
        "protein": 1,
        "carbs": 6,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Brócoli",
        "name_en": "Broccoli",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 34,
        "protein": 2.8,
        "carbs": 7,
        "fat": 0.4,
        "unit": "g",
    },
    {
        "name": "Coliflor",
        "name_en": "Cauliflower",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 25,
        "protein": 1.9,
        "carbs": 5,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Espinacas",
        "name_en": "Spinach",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 23,
        "protein": 2.9,
        "carbs": 3.6,
        "fat": 0.4,
        "unit": "g",
    },
    {
        "name": "Lechuga",
        "name_en": "Lettuce",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 15,
        "protein": 1.4,
        "carbs": 2.9,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Pepino",
        "name_en": "Cucumber",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 16,
        "protein": 0.7,
        "carbs": 3.6,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Apio",
        "name_en": "Celery",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 16,
        "protein": 0.7,
        "carbs": 3,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Puerro",
        "name_en": "Leek",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 61,
        "protein": 1.5,
        "carbs": 14,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Champiñones",
        "name_en": "Mushrooms",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 22,
        "protein": 3.1,
        "carbs": 3.3,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Espárragos",
        "name_en": "Asparagus",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 20,
        "protein": 2.2,
        "carbs": 3.9,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Alcachofa",
        "name_en": "Artichoke",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 47,
        "protein": 3.3,
        "carbs": 11,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Acelgas",
        "name_en": "Swiss chard",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 19,
        "protein": 1.8,
        "carbs": 3.7,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Col",
        "name_en": "Cabbage",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 25,
        "protein": 1.3,
        "carbs": 6,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Coles de Bruselas",
        "name_en": "Brussels sprouts",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 43,
        "protein": 3.4,
        "carbs": 9,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Remolacha",
        "name_en": "Beetroot",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 43,
        "protein": 1.6,
        "carbs": 10,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Calabaza",
        "name_en": "Pumpkin",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 26,
        "protein": 1,
        "carbs": 6.5,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Maíz dulce",
        "name_en": "Sweet corn",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 86,
        "protein": 3.2,
        "carbs": 19,
        "fat": 1.2,
        "unit": "g",
    },
    {
        "name": "Rúcula",
        "name_en": "Arugula",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 25,
        "protein": 2.6,
        "carbs": 3.6,
        "fat": 0.7,
        "unit": "g",
    },
    {
        "name": "Aceitunas verdes",
        "name_en": "Green olives",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 145,
        "protein": 1,
        "carbs": 4,
        "fat": 15,
        "unit": "g",
    },
    {
        "name": "Aceitunas negras",
        "name_en": "Black olives",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 115,
        "protein": 0.8,
        "carbs": 6,
        "fat": 11,
        "unit": "g",
    },
    {
        "name": "Jengibre",
        "name_en": "Ginger",
        "category": "Verduras",
        "category_en": "Vegetables",
        "calories": 80,
        "protein": 1.8,
        "carbs": 18,
        "fat": 0.8,
        "unit": "g",
    },
    # ===== FRUTAS / FRUITS =====
    {
        "name": "Manzana",
        "name_en": "Apple",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 52,
        "protein": 0.3,
        "carbs": 14,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Plátano",
        "name_en": "Banana",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 89,
        "protein": 1.1,
        "carbs": 23,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Naranja",
        "name_en": "Orange",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 47,
        "protein": 0.9,
        "carbs": 12,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Pera",
        "name_en": "Pear",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 57,
        "protein": 0.4,
        "carbs": 15,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Fresa",
        "name_en": "Strawberry",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 32,
        "protein": 0.7,
        "carbs": 8,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Uva",
        "name_en": "Grapes",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 69,
        "protein": 0.7,
        "carbs": 18,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Sandía",
        "name_en": "Watermelon",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 30,
        "protein": 0.6,
        "carbs": 8,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Melón",
        "name_en": "Melon",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 34,
        "protein": 0.8,
        "carbs": 8,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Melocotón",
        "name_en": "Peach",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 39,
        "protein": 0.9,
        "carbs": 10,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Limón",
        "name_en": "Lemon",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 29,
        "protein": 1.1,
        "carbs": 9,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Aguacate",
        "name_en": "Avocado",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 160,
        "protein": 2,
        "carbs": 9,
        "fat": 15,
        "unit": "g",
    },
    {
        "name": "Kiwi",
        "name_en": "Kiwi",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 61,
        "protein": 1.1,
        "carbs": 15,
        "fat": 0.5,
        "unit": "g",
    },
    {
        "name": "Mango",
        "name_en": "Mango",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 60,
        "protein": 0.8,
        "carbs": 15,
        "fat": 0.4,
        "unit": "g",
    },
    {
        "name": "Piña",
        "name_en": "Pineapple",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 50,
        "protein": 0.5,
        "carbs": 13,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Arándanos",
        "name_en": "Blueberries",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 57,
        "protein": 0.7,
        "carbs": 14,
        "fat": 0.3,
        "unit": "g",
    },
    {
        "name": "Frambuesas",
        "name_en": "Raspberries",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 52,
        "protein": 1.2,
        "carbs": 12,
        "fat": 0.7,
        "unit": "g",
    },
    {
        "name": "Pomelo",
        "name_en": "Grapefruit",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 42,
        "protein": 0.8,
        "carbs": 11,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Cereza",
        "name_en": "Cherry",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 63,
        "protein": 1.1,
        "carbs": 16,
        "fat": 0.2,
        "unit": "g",
    },
    {
        "name": "Papaya",
        "name_en": "Papaya",
        "category": "Frutas",
        "category_en": "Fruits",
        "calories": 43,
        "protein": 0.5,
        "carbs": 11,
        "fat": 0.3,
        "unit": "g",
    },
    # ===== FRUTOS SECOS / NUTS =====
    {
        "name": "Almendras",
        "name_en": "Almonds",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 579,
        "protein": 21,
        "carbs": 22,
        "fat": 50,
        "unit": "g",
    },
    {
        "name": "Nueces",
        "name_en": "Walnuts",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 654,
        "protein": 15,
        "carbs": 14,
        "fat": 65,
        "unit": "g",
    },
    {
        "name": "Avellanas",
        "name_en": "Hazelnuts",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 628,
        "protein": 15,
        "carbs": 17,
        "fat": 61,
        "unit": "g",
    },
    {
        "name": "Cacahuetes",
        "name_en": "Peanuts",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 567,
        "protein": 26,
        "carbs": 16,
        "fat": 49,
        "unit": "g",
    },
    {
        "name": "Pistachos",
        "name_en": "Pistachios",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 562,
        "protein": 20,
        "carbs": 28,
        "fat": 45,
        "unit": "g",
    },
    {
        "name": "Anacardos",
        "name_en": "Cashews",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 553,
        "protein": 18,
        "carbs": 30,
        "fat": 44,
        "unit": "g",
    },
    {
        "name": "Semillas de chía",
        "name_en": "Chia seeds",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 486,
        "protein": 17,
        "carbs": 42,
        "fat": 31,
        "unit": "g",
    },
    {
        "name": "Semillas de lino",
        "name_en": "Flax seeds",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 534,
        "protein": 18,
        "carbs": 29,
        "fat": 42,
        "unit": "g",
    },
    {
        "name": "Semillas de girasol",
        "name_en": "Sunflower seeds",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 584,
        "protein": 21,
        "carbs": 20,
        "fat": 51,
        "unit": "g",
    },
    {
        "name": "Semillas de calabaza",
        "name_en": "Pumpkin seeds",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 559,
        "protein": 30,
        "carbs": 11,
        "fat": 49,
        "unit": "g",
    },
    {
        "name": "Tahini",
        "name_en": "Tahini",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 595,
        "protein": 17,
        "carbs": 21,
        "fat": 54,
        "unit": "g",
    },
    {
        "name": "Mantequilla de cacahuete",
        "name_en": "Peanut butter",
        "category": "Frutos secos",
        "category_en": "Nuts",
        "calories": 588,
        "protein": 25,
        "carbs": 20,
        "fat": 50,
        "unit": "g",
    },
    # ===== ACEITES / OILS =====
    {
        "name": "Aceite de oliva",
        "name_en": "Olive oil",
        "category": "Aceites",
        "category_en": "Oils",
        "calories": 884,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "unit": "ml",
    },
    {
        "name": "Aceite de girasol",
        "name_en": "Sunflower oil",
        "category": "Aceites",
        "category_en": "Oils",
        "calories": 884,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "unit": "ml",
    },
    {
        "name": "Aceite de coco",
        "name_en": "Coconut oil",
        "category": "Aceites",
        "category_en": "Oils",
        "calories": 862,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "unit": "ml",
    },
    {
        "name": "Aceite de sésamo",
        "name_en": "Sesame oil",
        "category": "Aceites",
        "category_en": "Oils",
        "calories": 884,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "unit": "ml",
    },
    {
        "name": "Manteca de cerdo",
        "name_en": "Lard",
        "category": "Aceites",
        "category_en": "Oils",
        "calories": 902,
        "protein": 0,
        "carbs": 0,
        "fat": 100,
        "unit": "g",
    },
    # ===== SALSAS / SAUCES =====
    {
        "name": "Tomate triturado",
        "name_en": "Crushed tomato",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 32,
        "protein": 1.6,
        "carbs": 7,
        "fat": 0.4,
        "unit": "g",
    },
    {
        "name": "Tomate frito",
        "name_en": "Fried tomato sauce",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 65,
        "protein": 1.2,
        "carbs": 9,
        "fat": 3,
        "unit": "g",
    },
    {
        "name": "Ketchup",
        "name_en": "Ketchup",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 112,
        "protein": 1.5,
        "carbs": 27,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Mayonesa",
        "name_en": "Mayonnaise",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 680,
        "protein": 1,
        "carbs": 2,
        "fat": 75,
        "unit": "g",
    },
    {
        "name": "Mostaza",
        "name_en": "Mustard",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 66,
        "protein": 4,
        "carbs": 6,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Salsa de soja",
        "name_en": "Soy sauce",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 53,
        "protein": 8,
        "carbs": 5,
        "fat": 0.1,
        "unit": "ml",
    },
    {
        "name": "Vinagre",
        "name_en": "Vinegar",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 18,
        "protein": 0,
        "carbs": 0.1,
        "fat": 0,
        "unit": "ml",
    },
    {
        "name": "Salsa pesto",
        "name_en": "Pesto sauce",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 263,
        "protein": 6,
        "carbs": 8,
        "fat": 24,
        "unit": "g",
    },
    {
        "name": "Salsa bechamel",
        "name_en": "Bechamel sauce",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 120,
        "protein": 4,
        "carbs": 10,
        "fat": 7,
        "unit": "g",
    },
    {
        "name": "Guacamole",
        "name_en": "Guacamole",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 155,
        "protein": 2,
        "carbs": 9,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Alioli",
        "name_en": "Aioli",
        "category": "Salsas",
        "category_en": "Sauces",
        "calories": 480,
        "protein": 1,
        "carbs": 3,
        "fat": 52,
        "unit": "g",
    },
    # ===== ESPECIAS / SPICES =====
    {
        "name": "Sal",
        "name_en": "Salt",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 0,
        "protein": 0,
        "carbs": 0,
        "fat": 0,
        "unit": "g",
    },
    {
        "name": "Pimienta negra",
        "name_en": "Black pepper",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 251,
        "protein": 10,
        "carbs": 64,
        "fat": 3,
        "unit": "g",
    },
    {
        "name": "Pimentón",
        "name_en": "Paprika",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 282,
        "protein": 14,
        "carbs": 54,
        "fat": 13,
        "unit": "g",
    },
    {
        "name": "Comino",
        "name_en": "Cumin",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 375,
        "protein": 18,
        "carbs": 44,
        "fat": 22,
        "unit": "g",
    },
    {
        "name": "Orégano",
        "name_en": "Oregano",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 265,
        "protein": 9,
        "carbs": 69,
        "fat": 4,
        "unit": "g",
    },
    {
        "name": "Canela",
        "name_en": "Cinnamon",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 247,
        "protein": 4,
        "carbs": 81,
        "fat": 1,
        "unit": "g",
    },
    {
        "name": "Curry",
        "name_en": "Curry",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 325,
        "protein": 14,
        "carbs": 58,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Cúrcuma",
        "name_en": "Turmeric",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 354,
        "protein": 8,
        "carbs": 65,
        "fat": 10,
        "unit": "g",
    },
    {
        "name": "Perejil",
        "name_en": "Parsley",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 36,
        "protein": 3,
        "carbs": 6,
        "fat": 0.8,
        "unit": "g",
    },
    {
        "name": "Albahaca",
        "name_en": "Basil",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 23,
        "protein": 3.2,
        "carbs": 2.7,
        "fat": 0.6,
        "unit": "g",
    },
    {
        "name": "Romero",
        "name_en": "Rosemary",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 131,
        "protein": 3.3,
        "carbs": 21,
        "fat": 5.9,
        "unit": "g",
    },
    {
        "name": "Tomillo",
        "name_en": "Thyme",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 101,
        "protein": 5.6,
        "carbs": 24,
        "fat": 1.7,
        "unit": "g",
    },
    {
        "name": "Cilantro",
        "name_en": "Coriander",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 23,
        "protein": 2.1,
        "carbs": 3.7,
        "fat": 0.5,
        "unit": "g",
    },
    {
        "name": "Eneldo",
        "name_en": "Dill",
        "category": "Especias",
        "category_en": "Spices",
        "calories": 43,
        "protein": 3.5,
        "carbs": 7,
        "fat": 1.1,
        "unit": "g",
    },
    # ===== DULCES / SWEETS =====
    {
        "name": "Azúcar blanco",
        "name_en": "White sugar",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 387,
        "protein": 0,
        "carbs": 100,
        "fat": 0,
        "unit": "g",
    },
    {
        "name": "Azúcar moreno",
        "name_en": "Brown sugar",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 377,
        "protein": 0,
        "carbs": 97,
        "fat": 0,
        "unit": "g",
    },
    {
        "name": "Miel",
        "name_en": "Honey",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 304,
        "protein": 0.3,
        "carbs": 82,
        "fat": 0,
        "unit": "g",
    },
    {
        "name": "Mermelada",
        "name_en": "Jam",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 250,
        "protein": 0.4,
        "carbs": 65,
        "fat": 0.1,
        "unit": "g",
    },
    {
        "name": "Chocolate negro 70%",
        "name_en": "Dark chocolate 70%",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 598,
        "protein": 8,
        "carbs": 46,
        "fat": 43,
        "unit": "g",
    },
    {
        "name": "Chocolate con leche",
        "name_en": "Milk chocolate",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 535,
        "protein": 8,
        "carbs": 59,
        "fat": 30,
        "unit": "g",
    },
    {
        "name": "Cacao en polvo",
        "name_en": "Cocoa powder",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 228,
        "protein": 20,
        "carbs": 58,
        "fat": 14,
        "unit": "g",
    },
    {
        "name": "Sirope de agave",
        "name_en": "Agave syrup",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 310,
        "protein": 0.1,
        "carbs": 76,
        "fat": 0.5,
        "unit": "ml",
    },
    {
        "name": "Sirope de arce",
        "name_en": "Maple syrup",
        "category": "Dulces",
        "category_en": "Sweets",
        "calories": 260,
        "protein": 0,
        "carbs": 67,
        "fat": 0.1,
        "unit": "ml",
    },
]


def seed_foods():
    count = 0
    for f in FOODS:
        exists = db.session.execute(
            db.select(Food).where(Food.name == f["name"])
        ).scalar_one_or_none()
        if exists:
            continue
        db.session.add(Food(**f))
        count += 1
    db.session.commit()
    print(f"{count} foods inserted.")


if __name__ == "__main__":
    from app import create_app

    app = create_app()
    with app.app_context():
        seed_foods()
