"""add google_id to user

Revision ID: 42712ccef8ba
Revises: d84e5dbfbc72
Create Date: 2026-07-15 21:03:56.615823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42712ccef8ba'
down_revision = 'd84e5dbfbc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=120), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###
