"""add image attribution fields to recipe

Revision ID: 665fedbe3aa3
Revises: 67cfa26011d9
Create Date: 2026-07-17 13:18:11.943555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '665fedbe3aa3'
down_revision = '67cfa26011d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_photographer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_photographer_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_column('image_photographer_url')
        batch_op.drop_column('image_photographer_name')

    # ### end Alembic commands ###
