"""add past_due_since to subscription for grace period

Revision ID: d84e5dbfbc72
Revises: 044b660a22d0
Create Date: 2026-07-15 19:14:22.614030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd84e5dbfbc72'
down_revision = '044b660a22d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('past_due_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_column('past_due_since')

    # ### end Alembic commands ###
