"""add token fields to user

Revision ID: e31a2041b226
Revises: 
Create Date: 2026-04-21 14:17:52.938207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e31a2041b226'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('email_confirm_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_reset_token', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_token')
        batch_op.drop_column('email_confirm_token')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
