import { useState } from 'react'
import { useAuth } from '../../context/AuthContext'
import { createCheckoutSession, createPortalSession } from '../../services/subscriptionService'
import useLang from '../../hooks/useLang'

const Premium = () => {
    const { isPremium } = useAuth()
    const [loading, setLoading] = useState(false)
    const [portalLoading, setPortalLoading] = useState(false)
    const [error, setError] = useState(null)
    const lang = useLang()

    const handleUpgrade = async () => {
        setLoading(true)
        setError(null)
        try {
            const data = await createCheckoutSession()
            window.location.href = data.checkout_url
        } catch (err) {
            setError(lang === 'es'
                ? 'No se pudo iniciar el proceso de pago. Inténtalo de nuevo.'
                : 'Could not start the payment process. Please try again.'
            )
            setLoading(false)
        }
    }

    const handleManageSubscription = async () => {
        setPortalLoading(true)
        setError(null)
        try {
            const data = await createPortalSession()
            window.location.href = data.portal_url
        } catch (err) {
            setError(lang === 'es'
                ? 'No se pudo abrir la gestión de suscripción. Inténtalo de nuevo.'
                : 'Could not open subscription management. Please try again.'
            )
            setPortalLoading(false)
        }
    }

    return (
        <div className="min-h-screen flex items-center justify-center px-4 py-12 relative bg-neutral-950 overflow-hidden">

            <div
                className="absolute inset-0 opacity-25"
                style={{
                    backgroundImage: 'url(https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1600)',
                    backgroundSize: 'cover',
                    backgroundPosition: 'center',
                }}
            />
            <div className="absolute inset-0 bg-gradient-to-b from-neutral-950/70 via-neutral-950/90 to-neutral-950" />

            <div className="relative z-10 bg-neutral-900 border border-neutral-800 rounded-2xl shadow-2xl p-8 w-full max-w-lg">

                <div className="text-center mb-6">
                    <h1 className="text-2xl font-bold text-white mt-2">MealMind Premium</h1>
                    <p className="text-neutral-400 text-lg mt-1">
                        {lang === 'es'
                            ? 'Deja que la IA planifique tus comidas por ti.'
                            : 'Let AI plan your meals for you.'}
                    </p>
                </div>

                {isPremium ? (
                    <div className="text-center py-4">
                        <p className="text-lg font-semibold text-white mb-2">
                            {lang === 'es' ? 'Ya eres Premium' : "You're already Premium"}
                        </p>
                        <p className="text-neutral-400 text-lg mb-6">
                            {lang === 'es'
                                ? 'Tienes acceso completo al planificador con IA.'
                                : 'You have full access to the AI meal planner.'}
                        </p>

                        <button
                            onClick={handleManageSubscription}
                            disabled={portalLoading}
                            className="w-full bg-neutral-800 hover:bg-neutral-700 text-white font-semibold py-2.5 rounded-xl transition border border-neutral-700 disabled:opacity-60"
                        >
                            {portalLoading
                                ? (lang === 'es' ? 'Redirigiendo...' : 'Redirecting...')
                                : (lang === 'es' ? 'Gestionar suscripción' : 'Manage subscription')}
                        </button>

                        {error && <p className="text-red-400 text-lg text-center mt-3">{error}</p>}
                    </div>
                ) : (
                    <>
                        <div className="bg-neutral-800/60 rounded-xl p-5 mb-6 space-y-3">
                            <Feature text={lang === 'es' ? 'Planes semanales generados con IA.' : 'Weekly meal plans generated by AI.'} />
                            <Feature text={lang === 'es' ? 'Ajusta calorías máximas por comida.' : 'Set max calories per meal.'} />
                            <Feature text={lang === 'es' ? 'Basado en tus ingredientes preferidos.' : 'Based on your preferred ingredients.'} />
                            <Feature text={lang === 'es' ? 'Respeta tus alergias automáticamente.' : 'Automatically respects your allergies.'} />
                        </div>

                        <div className="text-center mb-6">
                            <p className="text-3xl font-bold text-white">
                                2,99€<span className="text-base font-normal text-neutral-500">
                                    {lang === 'es' ? '/mes' : '/month'}
                                </span>
                            </p>
                            <p className="text-lg text-neutral-400 mt-1">
                                {lang === 'es'
                                    ? '7 días de prueba gratis · Cancela cuando quieras'
                                    : '7-day free trial · Cancel anytime'}
                            </p>
                        </div>

                        <button
                            onClick={handleUpgrade}
                            disabled={loading}
                            className="w-full bg-orange-500 hover:bg-orange-600 text-white font-semibold py-2.5 rounded-xl transition active:scale-95 border-none"
                        >
                            {loading
                                ? (lang === 'es' ? 'Redirigiendo...' : 'Redirecting...')
                                : (lang === 'es' ? 'Empezar prueba gratis' : 'Start free trial')}
                        </button>

                        {error && <p className="text-red-400 text-lg text-center mt-3">{error}</p>}
                    </>
                )}
            </div>
        </div>
    )
}

const Feature = ({ text }) => (
    <div className="flex items-center gap-3">
        <span className="text-emerald-400">✓</span>
        <span className="text-white text-lg">{text}</span>
    </div>
)

export default Premium